name: Continuous Integration

on: [push, pull_request]

jobs:
  formatting:
    name: Check formatting
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Check formatting
      run: cargo fmt --all -- --check
