name: Nightly Checks

on:
  schedule:
    # Every night at midnight
    - cron: "0 0 * * *"
  workflow_dispatch:

jobs:
  # This won't build on GA environment because of missing TSS
  # libraries. To be reactivated later or to pass using Docker.
  dependencies:
    name: Check for unused dependencies
    if: false
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install latest Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly
      - name: Fetch submodules
        run: git submodule update --init
      - name: Install cargo udeps
        run: cargo install cargo-udeps --locked
      - name: Execute cargo udeps
        run: cargo udeps

  audit:
    name: Check for crates with security vulnerabilities
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install latest Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly
      - name: Install cargo audit
        run: cargo install cargo-audit
      - name: Execute cargo audit
        run: cargo audit

  coverage:
    name: Calculate code coverage
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build the container
        run: docker build -t ubuntucontainer tss-esapi/tests/ --file tss-esapi/tests/Dockerfile-ubuntu
      - name: Run the container
        run: docker run -v $(pwd):/tmp/rust-tss-esapi -w /tmp/rust-tss-esapi/tss-esapi --security-opt seccomp=unconfined ubuntucontainer /tmp/rust-tss-esapi/tss-esapi/tests/coverage.sh
